### ISSUE TITLE
Error in Custom Elements Example

### ISSUE THREAD

**Issue by andrerotband** [Xynonners/fletbox#1]
(.venv) C:\src\flet\airbnb>flet --version
0.9.0

SETUP completed in 0.01300287
http://127.0.0.1:56546
127.0.0.1 connected to route / in 0.01076174
127.0.0.1 connected to route / in 0.00594926
SETUP completed in 0.01399493
Unhandled error processing page session 6f959c82-8392-41ed-aaa9-51b5ba4e5a57: Traceback (most recent call last):
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_runtime\app.py", line 357, in on_session_created    session_handler(page)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 177, in wrapped_target     
    page.go(page.route)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_core\page.py", line 502, in go
    self.__on_route_change.get_sync_handler()(
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_core\event_handler.py", line 28, in __sync_handler
    h(r)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 162, in route_change       
    page.views.append(self.funcs[e.route](page))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 192, in wrapper
    ret = func(*args, page=page, builder=builder, **kwargs); builder = ret if isinstance(ret, Builder) else builder
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\flet\airbnb\fletbox_ex.py", line 21, in test
    builder.fm.Checkbox(ft.BoxShape.CIRCLE, value=False, disabled=False)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: '_shell' object has no attribute 'Checkbox'

Unhandled error processing page session 9b49d227-29f8-464d-8d57-2c8460ca0e71: Traceback (most recent call last):
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_runtime\app.py", line 357, in on_session_created    session_handler(page)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 177, in wrapped_target     
    page.go(page.route)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_core\page.py", line 502, in go
    self.__on_route_change.get_sync_handler()(
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\flet_core\event_handler.py", line 28, in __sync_handler
    h(r)
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 162, in route_change       
    page.views.append(self.funcs[e.route](page))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\flet\airbnb\.venv\Lib\site-packages\fletbox\fletbox.py", line 192, in wrapper
    ret = func(*args, page=page, builder=builder, **kwargs); builder = ret if isinstance(ret, Builder) else builder
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\flet\airbnb\fletbox_ex.py", line 21, in test
    builder.fm.Checkbox(ft.BoxShape.CIRCLE, value=False, disabled=False)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: '_shell' object has no attribute 'Checkbox'

**Comment by Xynonners** [comment]
Yeah, flet_material's Checkbox control is named CheckBox. Should be fixed now.

**Comment by andrerotband** [comment]
Thank you!

Please, do you have examples of apps in your framework to share?
